services:
  - type: web
    name: cryptomoose
    env: node
    buildCommand: npm install
    startCommand: node server/server.js
    runtime: node
    nodeVersion: 18.x
    rootDir: /
    healthCheckPath: /healthz
    healthCheckTimeout: 60
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
